libraries/AP_HAL_ChibiOS/RCOutput.cpp
..In order to get one pulse every controller loop. Useful to drive digital servos on planes. 
loop rate at 100Hz -> servo output at 100Hz in sync with the loop.
=> Regularise ONESHOT output

libraries/AP_OLC/AP_OLC.cpp, libraries/AP_OLC/AP_OLC.h, libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
This chops of the first four digits from the OSD plus code since you don't need them if you have a reference location within ~40 km. I also added the 11th digit to increase the precision from 13.9 meters to 2.8 x 3.5 meters. Together, this saves three characters on the OSD. To keep things simple I didn't add parameters or defines to configure the formatting. This way should work fine for everyone.
=> Shorten OSD plus codes

ArduPlane/AP_Arming.cpp, ArduPlane/AP_Arming.h, ArduPlane/RC_Channel.cpp, ArduPlane/RC_Channel.h, ArduPlane/is_flying.cpp, ArduPlane/servos.cpp, libraries/AP_Notify/AP_Notify.h, libraries/AP_OSD/AP_OSD_Screen.cpp
- If an attempt is made to disarm the plane with arming switch while flying the plane will not be disarmed but the throttle will be cut
- If the throttle is cut following a disarm request while flying in an auto throttle mode the mode is switched to FBWA. The previous mode is then restored if the arming switch is put in the arming position again and the mode hasn't been changed from FBWA
- When the throttle is cut a message is displayed on the OSD and the throttle element and disarm symbol next to the flight mode are blinking
- The plane will disarm if the arming switch was put in disarm position while flying and then later the plane stops flying (crash or landing)
=> Plane: make arming switch/channel safe to use

ArduPlane/reverse_thrust.cpp
This is solving the issue where the motor(s) will start running at full reverse throttle if you have reverse throttle configured but you set `THR_MIN` >= 0
=> Fix motors running at full reverse throttle when arming and THR_MIN>=0 when reverse thrust is configured

libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
- The TECS TCONST param which is used to set the aggressiveness was ignored when calculating the throttle FF term
- The throttle value is directly related to the rate of change of the demanded airspeed so when you were changing the demanded air speed even a little it would jerk the throttle
This patch on top of fixing these issues makes available 3 new parameters to tune how the applied airspeed changes when requested:
- SPDRATE_ACC sets the rate of acceleration of the applied speed demand
- SPDRATE_MIN/MAX set the minimum and maximum rate at which the applied speed demand changes
=> Fix the TECS

libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
Apply the throttle slew rate:
- when airspeed is used or not
- in all cases: starting to glide and underspeed
- before the throttle value is sent to the OSD so that it is reflected in the OSD throttle element
=> TECS: apply throttle slew rate in all cases

ArduPlane/navigation.cpp
This adds a hard-coded 10% deadband around the center throttle position to make it easier to target exactly the configured cruise airspeed. This only applies when using the center stick position for cruise airpeed (bit 2 of `FLIGHT_OPTIONS`).
I am still not 100% sure if the throttle range in this part of the code is 0.0-1.0 or 0-100. For now I assumed it is the former but I have not tested this yet.
=> Add deadband for cruise airspeed control

libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
Note that these won't work right if your board trim is not 0 or more exactly if what your board's accelerometer measures when the AHRS says it is level is not the gravitational acceleration
=> OSD: add vehicle acceleration elements

libraries/AP_OSD/AP_OSD_Screen.cpp
=> OSD: display rangefinder altitude only when data is available and sensor in range

Tools/autotest/param_metadata/param.py, libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.h, libraries/AP_OSD/AP_OSD_Screen.cpp
- Adds params for low and critical Wh capacity
- Adds param for minimum remaining energy for arming
- Adds failsafe on low or critical Wh capacity
- Blink OSD Ah and Wh counters when remaining capacity is lower than the specified low capacity
- Display message when low and critical Wh capacity are reached
- Add option bit in BATT_OPTIONS to use Wh capacity instead of mAh capacity for percentage calculations
=> Battery monitoring improvements

libraries/AP_OSD/AP_OSD_Screen.cpp
Offset batt voltage x by 1 if bar not shown so that there is no offset between when the bar is shown (battery % available) and when the bar is not shown (battery % not available)
=> OSD: offset batt voltage x by 1 if bar not shown

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.h, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
- Add average efficiency
- Use energy consumed without power losses for efficiency calculations
- Power now includes losses
- Possibility to display remaining Wh and Ah
- The OSD voltage elements will now blink the battery symbol (low capacity) separately from the voltage (low voltage)
- Some code fixes and improvement
=> Even more battery monitoring improvements

ArduPlane/Attitude.cpp
- Apply STAB_PITCH_DOWN during reverse thrust (removes step between 0 and negative throttle)
- Add square curve to applied down angle to match physics
=> Plane: improve STAB_PITCH_DOWN handling

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/reverse_thrust.cpp, libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
Adds THR_EXPO setting adding a configurable square curve to the throttle. Should be set to either 0 or 100 (or close to)
- 0% (default) gives linear propulsion power control
- 100% square curve gives linear airspeed control
=> Plane: add throttle curves

libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
- only accumulate mah/wh consumed when armed
- only update wind max/avg after the plane has been flying more than 30s
=> OSD: improve stats

ArduPlane/RC_Channel.h, ArduPlane/servos.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels_VarInfo.h
It is possible to disable it with bit 22 in `RC_OPTIONS`
=> Plane: enable throttle battery compensation in manual mode

ArduPlane/Parameters.cpp, ArduPlane/mode_loiter.cpp, Tools/autotest/arduplane.py
...and disable stick mixing by default
=> Plane: enable loiter alt control even with stick mixing disabled

ArduPlane/Plane.h, ArduPlane/servos.cpp, ArduPlane/system.cpp
Was causing the output throttle displayed on the OSD and the GCS to sometimes not show the right value
=> Plane: fix throttle output unsynchronized concurrent access

ArduPlane/navigation.cpp
Doesn't change anything for the plane code itself but allows to sync the demanded airspeed displayed on the OSD to what should be the real airspeed corresponding to the demanded throttle in auto throttle modes
=> Plane: clip min demanded airspeed to trim if not using airspeed

ArduPlane/navigation.cpp
Allows to have a visual reference of what the airspeed should be if the demanded airspeed OSD element is used
=> Plane: set dem airspeed at minimum when gliding even when not using airspeed

libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
The purpose of this is for management tools to be able to identify which aircraft they are talking to.
=> All vehicles: add unique identifier

ArduPlane/servos.cpp
Use target airspeed from user input instead of TECS target airspeed when the throttle is suppressed making it possible to test auto flaps on the ground
=> Plane: use target airspeed for auto flaps when throttle is suppressed

libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
The `RF_Mode` byte in the CRSF protocol is used to communicate the current RF parameters between the RX and the FC.
The value is an enum, where each value represents a different mode of operation, e.g in ELRS mode 7 is 500Hz LoRa.
For some unknown reason, the `RF_Mode` was being capped to a max of 7 in the code. This creates problems when using the `master` branch on ELRS (soon to become v3.0), which uses modes >7. Removing the cap to allow showing these modes.
=> Un-cap RF_Mode for CRSF protocol

ArduPlane/AP_Arming.cpp, ArduPlane/AP_Arming.h
Disarming with the arming channel during flight doesn't disarm the plane but just cuts throttle and allows rearming without doing the arming checks since V10.0. Now this change also enables emergency landing (forcing FBWA during FS) when throttle cut is enabled allowing to land away from home if the plane can't make it without triggering RTL when losing radio signal because of the proximity to the ground.
Closes #215
=> Plane: throttle cut emergency landing

ArduPlane/AP_Arming.cpp, ArduPlane/quadplane.cpp, ArduPlane/servos.cpp, libraries/AP_OSD/AP_OSD_Screen.cpp
While flying stop motors in Q modes if arming switch put in disarmed position and throttle at 0. Previously the motors would only be stopped in forward flight modes while flying and arming switch put in disarmed position.
=> Plane: throttle cut improvement for quadplane/tailsitter
